path: C:/Users/ithak/OneDrive/Apps/YOLO PROJACTE IPF

# מצביעים ישירות לתת-תיקיית ה-images בכל split
train: train/images
val: valid/images     # אם אצלך זה val → כתוב val/images
test: test/images

nc: 6
names:
  0: cluster
  1: durandal
  2: lgb
  3: m
  4: mk
  5: moab
