train: r"C:\Users\ithak\OneDrive\Apps\My First Project.v2i.yolov11\train\images"
val: r"C:\Users\ithak\OneDrive\Apps\My First Project.v2i.yolov11\valid\images"
test: r"C:\Users\ithak\OneDrive\Apps\My First Project.v2i.yolov11\test\images"

nc: 5
names: ['cluster', 'durandal', 'lgb', 'mk', 'moab']


